version: '3'

services:
  postgres:
    container_name: "postgres"
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_DB}
    volumes:
      - postgres_storage_new:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - custom
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_NAME} -d ${DB_DB}"]
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: [ '/smit_app/docker/app.sh' ]
    env_file:
      - .env
    depends_on:
      - postgres
    ports:
      - '8000:8000'
    networks:
      - custom
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/default/ready" ]
      interval: 10s
      timeout: 5s
      retries: 3



networks:
  custom:
    driver: bridge

volumes:
  postgres_storage_new:
    driver: local
