"""init

Revision ID: a61d06dc8eb0
Revises: 
Create Date: 2024-12-01 00:41:33.669074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a61d06dc8eb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_accessions',
    sa.Column('published_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariffs',
    sa.Column('category_type', sa.String(length=32), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('date_accession_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['date_accession_id'], ['date_accessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tariffs')
    op.drop_table('date_accessions')
    # ### end Alembic commands ###
